# Generated by Django 5.0.6 on 2026-09-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('profile', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('engine', models.CharField(default='ai', max_length=32)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('ranking_world', models.PositiveIntegerField(blank=True, null=True)),
                ('ranking_national', models.PositiveIntegerField(blank=True, null=True)),
                ('acceptance_rate', models.FloatField(blank=True, help_text='0–1. 0.12 means 12% of applicants are admitted.', null=True)),
                ('tuition_min_eur', models.PositiveIntegerField(blank=True, null=True)),
                ('tuition_max_eur', models.PositiveIntegerField(blank=True, null=True)),
                ('living_cost_eur', models.PositiveIntegerField(blank=True, null=True)),
                ('housing_cost_eur', models.PositiveIntegerField(blank=True, null=True)),
                ('application_fee_eur', models.PositiveIntegerField(blank=True, null=True)),
                ('scholarship_notes', models.TextField(blank=True)),
                ('scholarship_max_eur', models.PositiveIntegerField(blank=True, null=True)),
                ('min_ielts', models.FloatField(blank=True, null=True)),
                ('avg_ielts', models.FloatField(blank=True, null=True)),
                ('min_sat', models.PositiveIntegerField(blank=True, null=True)),
                ('avg_sat', models.PositiveIntegerField(blank=True, null=True)),
                ('sat_required', models.BooleanField(default=False)),
                ('min_gpa', models.FloatField(blank=True, help_text='On a 4.0 scale.', null=True)),
                ('avg_gpa', models.FloatField(blank=True, null=True)),
                ('language_of_instruction', models.CharField(blank=True, max_length=120)),
                ('majors', models.JSONField(blank=True, default=list)),
                ('application_deadline', models.CharField(blank=True, help_text="Free text, e.g. '15 January' or '2026-01-15'.", max_length=120)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('campus_map_url', models.URLField(blank=True, help_text='Official interactive or PDF campus map.')),
                ('has_housing', models.BooleanField(default=False)),
                ('image_front', models.URLField(blank=True, max_length=700)),
                ('image_inside', models.URLField(blank=True, max_length=700)),
                ('image_housing', models.URLField(blank=True, max_length=700)),
                ('image_credits', models.JSONField(blank=True, default=dict)),
                ('images_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('data_source', models.CharField(choices=[('provided', 'Provided database'), ('seed', 'Bundled demo data'), ('manual', 'Entered by hand')], default='provided', max_length=20)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ranking_world', 'name'],
                'indexes': [models.Index(fields=['country', 'city'], name='api_univers_country_95588e_idx'), models.Index(fields=['tuition_min_eur'], name='api_univers_tuition_eef311_idx')],
            },
        ),
    ]
